### PR TITLE
Pull the updated file first before trying to read from it.

### PR DESCRIPTION
**Pull request by zackigoldberg**

### CODE REVIEW

**Review by tgallant — COMMENTED** [review]
it should be possible to pull directly from the URL. why doesn't that work?

**Comment by zackigoldberg** [comment]
> it should be possible to pull directly from the URL. why doesn't that work?

So the redoc link that Docusaurus provides tries to download everything instead of serving a static copy. As far as I can tell that is the reason why this didn't work

**Comment by tgallant** [comment]
> So the redoc link that Docusaurus provides tries to download everything instead of serving a static copy

what does that mean? what is different from what docusaurus provides vs a static copy?

**Comment by zackigoldberg** [comment]
> > So the redoc link that Docusaurus provides tries to download everything instead of serving a static copy
> 
> what does that mean? what is different from what docusaurus provides vs a static copy?

So, something like swagger-ui will display the docs as a yaml/json file in the browser, which can be read as the response to an api call. However, the Redocusaurus/redoc.yaml automatically downloads the file, and the generation script doesn't expect a download it expects what's in the file itself, either from a static site as the response to an http request, or from a local file that is opened. So my change first downloads the file locally, then uses the local copy to regenerate the docs.

**Comment by tgallant** [comment]
@zackigoldberg can you link to some logs of where this is failing?

**Comment by zackigoldberg** [comment]
https://github.com/lilt/lilt-python/actions/runs/8531090113

**Review by tgallant — APPROVED** [review]

**Pull request merged**
